### ISSUE TITLE
semantic release for module

### ISSUE THREAD

**Issue by hairmare** [adfinis-sygroup/terraform-azurerm-adfinis-governance#4]
Hi Hofi

To publish this module on the terraform registry we would need to have semantic tags because the registry complains otherweise:

> No release tags found that are in the valid format. Please ensure your repository has at least one tag formatted 'vVERSION' where VERSION is a semantic version.

I propose we add a release actions like [this one](https://github.com/adfinis/openshift-etcd-backup/blob/d18a29e258eb09fce61c17d9d20867e45448e1ad/.github/workflows/semantic-release.yaml) that uses the commit message on each merge to decide if/how a new release should be made.

I'll prepare a PR to implement this and get us started with 0.x.y releases if that is ok.

**Comment by karras** [comment]
Sounds good, thanks a lot!
